// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spine/base/field_path.proto

// Protobuf Java Version: 3.25.2
package io.spine.base;

/**
 * <pre>
 * Field path provides field names of nested messages.
 *
 * The first entry in the names list is a name of a field in the root message.
 * The second entry is the name of the field in the nested message, and so on.
 *
 * For example, consider the following message declarations:
 *
 *     message CustomerAccount {
 *       User user = 1;
 *     }
 *
 *     message User {
 *       string name = 1;
 *     }
 *
 * The field path for `name` field of the `User` message enclosed into the `CustomerAccount`
 * is ["user", "name"].
 * </pre>
 *
 * Protobuf type {@code spine.base.FieldPath}
 */
public final class FieldPath extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:spine.base.FieldPath)
    FieldPathOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldPath.newBuilder() to construct.
  private FieldPath(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldPath() {
    fieldName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldPath();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.spine.base.FieldPathProto.internal_static_spine_base_FieldPath_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.spine.base.FieldPathProto.internal_static_spine_base_FieldPath_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.spine.base.FieldPath.class, io.spine.base.FieldPath.Builder.class);
  }

  public static final int FIELD_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList fieldName_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Unqualified field names.
   * </pre>
   *
   * <code>repeated string field_name = 1;</code>
   * @return A list containing the fieldName.
   */
  public com.google.protobuf.ProtocolStringList
      getFieldNameList() {
    return fieldName_;
  }
  /**
   * <pre>
   * Unqualified field names.
   * </pre>
   *
   * <code>repeated string field_name = 1;</code>
   * @return The count of fieldName.
   */
  public int getFieldNameCount() {
    return fieldName_.size();
  }
  /**
   * <pre>
   * Unqualified field names.
   * </pre>
   *
   * <code>repeated string field_name = 1;</code>
   * @param index The index of the element to return.
   * @return The fieldName at the given index.
   */
  public java.lang.String getFieldName(int index) {
    return fieldName_.get(index);
  }
  /**
   * <pre>
   * Unqualified field names.
   * </pre>
   *
   * <code>repeated string field_name = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldName at the given index.
   */
  public com.google.protobuf.ByteString
      getFieldNameBytes(int index) {
    return fieldName_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fieldName_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldName_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < fieldName_.size(); i++) {
        dataSize += computeStringSizeNoTag(fieldName_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFieldNameList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.spine.base.FieldPath)) {
      return super.equals(obj);
    }
    io.spine.base.FieldPath other = (io.spine.base.FieldPath) obj;

    if (!getFieldNameList()
        .equals(other.getFieldNameList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFieldNameCount() > 0) {
      hash = (37 * hash) + FIELD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFieldNameList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.spine.base.FieldPath parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spine.base.FieldPath parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spine.base.FieldPath parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spine.base.FieldPath parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spine.base.FieldPath parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.spine.base.FieldPath parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.spine.base.FieldPath parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spine.base.FieldPath parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.spine.base.FieldPath parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.spine.base.FieldPath parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.spine.base.FieldPath parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.spine.base.FieldPath parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.spine.base.FieldPath prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Field path provides field names of nested messages.
   *
   * The first entry in the names list is a name of a field in the root message.
   * The second entry is the name of the field in the nested message, and so on.
   *
   * For example, consider the following message declarations:
   *
   *     message CustomerAccount {
   *       User user = 1;
   *     }
   *
   *     message User {
   *       string name = 1;
   *     }
   *
   * The field path for `name` field of the `User` message enclosed into the `CustomerAccount`
   * is ["user", "name"].
   * </pre>
   *
   * Protobuf type {@code spine.base.FieldPath}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spine.base.FieldPath)
      io.spine.base.FieldPathOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.spine.base.FieldPathProto.internal_static_spine_base_FieldPath_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.spine.base.FieldPathProto.internal_static_spine_base_FieldPath_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.spine.base.FieldPath.class, io.spine.base.FieldPath.Builder.class);
    }

    // Construct using io.spine.base.FieldPath.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fieldName_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.spine.base.FieldPathProto.internal_static_spine_base_FieldPath_descriptor;
    }

    @java.lang.Override
    public io.spine.base.FieldPath getDefaultInstanceForType() {
      return io.spine.base.FieldPath.getDefaultInstance();
    }

    @java.lang.Override
    public io.spine.base.FieldPath build() {
      io.spine.base.FieldPath result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.spine.base.FieldPath buildPartial() {
      io.spine.base.FieldPath result = new io.spine.base.FieldPath(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.spine.base.FieldPath result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        fieldName_.makeImmutable();
        result.fieldName_ = fieldName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.spine.base.FieldPath) {
        return mergeFrom((io.spine.base.FieldPath)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.spine.base.FieldPath other) {
      if (other == io.spine.base.FieldPath.getDefaultInstance()) return this;
      if (!other.fieldName_.isEmpty()) {
        if (fieldName_.isEmpty()) {
          fieldName_ = other.fieldName_;
          bitField0_ |= 0x00000001;
        } else {
          ensureFieldNameIsMutable();
          fieldName_.addAll(other.fieldName_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFieldNameIsMutable();
              fieldName_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList fieldName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFieldNameIsMutable() {
      if (!fieldName_.isModifiable()) {
        fieldName_ = new com.google.protobuf.LazyStringArrayList(fieldName_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @return A list containing the fieldName.
     */
    public com.google.protobuf.ProtocolStringList
        getFieldNameList() {
      fieldName_.makeImmutable();
      return fieldName_;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @return The count of fieldName.
     */
    public int getFieldNameCount() {
      return fieldName_.size();
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param index The index of the element to return.
     * @return The fieldName at the given index.
     */
    public java.lang.String getFieldName(int index) {
      return fieldName_.get(index);
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fieldName at the given index.
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes(int index) {
      return fieldName_.getByteString(index);
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param index The index to set the value at.
     * @param value The fieldName to set.
     * @return This builder for chaining.
     */
    public Builder setFieldName(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFieldNameIsMutable();
      fieldName_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param value The fieldName to add.
     * @return This builder for chaining.
     */
    public Builder addFieldName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFieldNameIsMutable();
      fieldName_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param values The fieldName to add.
     * @return This builder for chaining.
     */
    public Builder addAllFieldName(
        java.lang.Iterable<java.lang.String> values) {
      ensureFieldNameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fieldName_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldName() {
      fieldName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unqualified field names.
     * </pre>
     *
     * <code>repeated string field_name = 1;</code>
     * @param value The bytes of the fieldName to add.
     * @return This builder for chaining.
     */
    public Builder addFieldNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFieldNameIsMutable();
      fieldName_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:spine.base.FieldPath)
  }

  // @@protoc_insertion_point(class_scope:spine.base.FieldPath)
  private static final io.spine.base.FieldPath DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.spine.base.FieldPath();
  }

  public static io.spine.base.FieldPath getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldPath>
      PARSER = new com.google.protobuf.AbstractParser<FieldPath>() {
    @java.lang.Override
    public FieldPath parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FieldPath> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldPath> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.spine.base.FieldPath getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

